athphane/userbot

- userbot/plugins/spam.py
> Updated .help for .spam

- userbot/plugins/spam.py
sorry for the missing qoute on last request. here i have double checked everything
> missing qoute

- requirements.txt
Breaking change > Remember to do pip install -r requirements.txt
> - Added PTable needed for corona module

- userbot/plugins/corona.py
Actually no, I just made it a bit more pretty
> - Completely redo this module > jk

- userbot/plugins/memes/random_images.py
panda, redpanda, bird, fox, koala
> Added New Animals to random_images.py

- userbot/plugins/afk.py
> - AFK auto unset

- requirements.txt
- userbot/helpers/utility.py
- userbot/plugins/afk.py
> - Added last seen to akf module.

- userbot/helpers/utility.py
- userbot/plugins/memes/text.py
- Changed from random to every 2nd to every other character when generating mock text
> - Mock text fix

- userbot/helpers/aiohttp.py
- userbot/plugins/git.py
I don't know anymore, life is all about adventure
> - Github graph

- userbot/plugins/1start.py
Fixed unresponsive id output and added detailed information to the output.
> cleanup to id command

- userbot/plugins/memes/emoji.py
New Telegram beta's 'soccer' dice animation is here!
> added new Special Emoji

- README.md
Since now this supports Heroku we can move on with replacing One Click Deploy line
> updated README.md to fit in with correct details

- README.md
Termux users cannot use `restar` command.
> Added Known issues

- requirements.txt
- userbot/helpers/tiktokHelper.py
- userbot/plugins/download_tiktok.py
added .t to download tiktoks (might work for yt too)
> added tiktok downloader

- userbot/plugins/memes/some-random-api/animals.py
- userbot/plugins/memes/some-random-api/animu.py
updated the some-random-api endpoint to the correct url
> Fix animals

- userbot/plugins/memes/some-random-api/animu.py
updated the some-random-api endpoint to the correct url and fixed a typo in the json response in the quote `data[characther]`
> update api endpoint and fix a typo in json response

- .build/Dockerfile
- .build/docker-compose.yml
- .build/setup
- .dockerignore
- docker-compose.yml
- userbot/__init__.py
manually building and running works
> Containerized build

- .build/dev.Dockerfile
- docker-compose.yml
- requirements.txt
- userbot/plugins/text_replacement.py
- userbot/plugins/video_dl.py
Main changes:
- Remove text replacement for  ddinstagram.com > ddinstagram.com
- Added support for Tiktok and Instgram video download and upload 
- Video URL will be in uploaded video caption (to open from web or app)
- Remove tracker links from Tiktok videos (hide who shared the video)
- If shared link contains only the link, this message will be deleted. 
- If shared link contains other text, this text message will not be deleted
-  `docker compose up`  in project root will auto build image with requirements for development use, with latest requirements.txt, if requirements.txt is updated, run `docker compose build` to rebuild image
> Download Videos and upload them

- userbot/plugins/1start.py
The .uptime command now uses the same code that is used for calculating uptime in the .alive command.
> Fix Uptime Command

- userbot/plugins/video_dl.py
Adds a .dl command that lets you download from a video url that someone else sends
> Add .dl command
